In [1]:
import numpy as np

In [4]:
print(np.__version__)

1.22.1


# creating a 1D array

In [5]:
np.array([0,1,2,3,4])

array([0, 1, 2, 3, 4])


# boolean aray

In [8]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
a =np.full((2,2),99)
print(a)

[[99 99]
 [99 99]]


# extracting odd numbers from arr

In [22]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
a = arr[arr%2 == 1]
print(a)

[1 3 5 7 9]


In [23]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

# extracting even numbers from arr

In [24]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr%2 == 0]

array([0, 2, 4, 6, 8])

# replace all odd numbers in arr

In [32]:
arr = np.array([0,1,2,3,4,5,6,7])
arr[arr%2 == 1] = -1
print(arr)



[ 0 -1  2 -1  4 -1  6 -1]


# replace items that satisfy a condition without affecting the original array

In [33]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array = (arr[arr%2 == 1] ,-1,arr)
array

(array([1, 3, 5, 7, 9]), -1, array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [35]:
#confusing

# reshaping an array

In [36]:
#1D array to 2D array with 2 rows input

In [37]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
# Setting to -1 automatically decides the number of cols

# how to stack two arrays vertically

In [52]:
a = np.arange(10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
b = np.repeat(1, 10).reshape(2,-1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [64]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
stack =np.concatenate((a,b),axis=0)
stack

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [63]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
stack =np.concatenate((a,b),axis=1)
stack

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# stack two arrays horizontally

In [65]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
stack =np.concatenate((a,b),axis=1)
stack

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# generate custom sequences in numpy without hardcoding

In [67]:
a = np.array([1,2,3])
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [68]:
# it worked my beautiful brain but it can also be done as

In [69]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [70]:
np.r_[np.repeat(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [74]:
 np.tile(a, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

# getting common items between two python numpy arrays

In [79]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [77]:
#intersect1d

# remove from one array those items that exist in another

In [88]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)



array([1, 2, 3, 4])

In [89]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(b,a)


array([6, 7, 8, 9])

# Get the positions where elements of a and b match Input:

In [91]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [93]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a!=b)

(array([0, 2, 4, 6, 8, 9], dtype=int64),)

# Get all items between 5 and 10 from a. Input:

In [99]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a > 5) & (a <=0))
a[index]

array([ 6,  9, 10])